### ISSUE TITLE
Injecting HttpClient

### ISSUE THREAD

**Issue by mrcunninghamz** [ara-framework/hypernova-angular#3]
I'm trying to inject httpclient to a component...

this is my module:
```
import { NgModule }         from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { TemperatureComponent } from './Temperature.component';
import { WeatherService } from './WeatherService';

@NgModule({
  imports: [
    HttpClientModule
  ],
  providers: [ WeatherService ],
  declarations: [
    TemperatureComponent,
  ]
})
export class TemperatureModule {}
```

with my weather service:

```
@Injectable({
  providedIn: 'root'
})
export class WeatherService {
  constructor(private http: HttpClient) {}

  getWeatherReport() {
    return this.http.get<WeatherReport>("http://api.openweathermap.org/data/2.5/weather?zip=55330,us&units=Imperial")
  }
}

```
I get a 
`Can't resolve all parameters for WeatherService: (?)`

when I call http://localhost:3000/batch

**Comment by marconi1992** [comment]
Hi @mrcunninghamz, I reproduced the issue.  We'll take a look and fix it. Thanks.

**Comment by marconi1992** [comment]
@mrcunninghamz It was fixed on https://github.com/ara-framework/create-hypernova-angular/pull/11.

If you have already a project created with `create-hypernova-angular`, you need to replace `core-js/proposals/reflect-metadata` with `core-js/features/reflect` in there `browser.main.ts` and `server.main.ts`.

Also, you need to update the `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "typeRoots": ["node_modules/@types"]
  },
  "exclude": ["node_modules"]
}
```

**Comment by mrcunninghamz** [comment]
@marconi1992 

sorry for not getting back for months. I'm not currently using ara framework, but if this issue is fixed please feel free to close it.

**Comment by marconi1992** [comment]
no problem!
